CREATE DATABASE DOANLTTQ_QUANLYHANGHOA
USE DOANLTTQ_QUANLYHANGHOA
CREATE TABLE LOAIHANG (
	MAHANG VARCHAR(30) PRIMARY KEY,
	TENHANG NVARCHAR(100),
	DVT NVARCHAR(10) )

CREATE TABLE NHANVIEN (
	MANV VARCHAR(15) PRIMARY KEY,
	HOTEN NVARCHAR(50),
	NGSINH SMALLDATETIME,
	CMND VARCHAR(15),
	DIACHI NVARCHAR(100),
	NGVAOLAM SMALLDATETIME,
	MATKHAU VARCHAR(200),
	GMAIL VARCHAR(200))

CREATE TABLE NHAPHANG (
	MAHANG VARCHAR(30),
	MALO INT,
	NGNHAP SMALLDATETIME,
	HANSD SMALLDATETIME,
	SOLUONG INT,
	DONGIA MONEY,
	MANV VARCHAR(15),
	CONSTRAINT PK_NHAPHANG PRIMARY KEY (MAHANG, MALO),
	CONSTRAINT FK_NHAPHANG_LOAIHANG FOREIGN KEY (MAHANG)
			REFERENCES LOAIHANG(MAHANG),
	CONSTRAINT FK_NHAPHANG_NHANVIEN FOREIGN KEY (MANV)
			REFERENCES NHANVIEN (MANV))

CREATE TABLE CUAHANG (
	MACH VARCHAR(20) PRIMARY KEY,
	TENCH NVARCHAR(50),
	MACHUCH VARCHAR(15),
	NGTHANHLAP SMALLDATETIME,
	CONSTRAINT FK_CUAHANG_NHANVIEN FOREIGN KEY (MACHUCH)
			REFERENCES NHANVIEN (MANV))

CREATE TABLE HOADON (
	MAHD VARCHAR(30) PRIMARY KEY,
	NGHOADON SMALLDATETIME,
	MANV VARCHAR(15),
	TRIGIA MONEY,
	CONSTRAINT FK_HOADON_NHANVIEN FOREIGN KEY (MANV)
			REFERENCES NHANVIEN (MANV))

CREATE TABLE CTHD (
	MAHD VARCHAR(30),
	MAHANG VARCHAR(30),
	SOLUONG INT,
	MALO INT,
	CONSTRAINT PK_CTHD PRIMARY KEY (MAHD, MAHANG),
	CONSTRAINT FK_CTHD_HD FOREIGN KEY (MAHD)
			REFERENCES HOADON (MAHD),
	CONSTRAINT FK_CTHD_LH FOREIGN KEY (MAHANG)
			REFERENCES LOAIHANG (MAHANG))

SET DATEFORMAT DMY